DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS schedules;

CREATE TABLE users (
id SERIAL PRIMARY KEY,
firstname VARCHAR(255) NOT NULL,
lastname VARCHAR(255) NOT NULL,
email VARCHAR(255) NOT NULL,
password VARCHAR(255) NOT NULL
);

CREATE TABLE schedules (
id SERIAL PRIMARY KEY,
id_user INT NOT NULL,
day SMALLINT NOT NULL,
start_at TIME  NOT NULL,
end_at TIME NOT NULL,
FOREIGN KEY (id_user) 
REFERENCES users(id) 
ON DELETE CASCADE
ON UPDATE CASCADE 
);
